#!/bin/bash
source $OPENSHIFT_CARTRIDGE_SDK_BASH

echo "Stopping nginx"

VERSION=1.7.2.1

APPROOT=~/app-root/repo/usr/$VERSION
export LD_LIBRARY_PATH=$APPROOT/luajit/lib

LAPIS=$APPROOT/rocks/bin
NGINX=$APPROOT/nginx/sbin/nginx

eval "'$NGINX' -c '$LAPIS/nginx.conf' -s stop"